server:
  port: 8082

spring:
  application:
    name: cart-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    fon.cartservice: debug
