server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

spring.jpa.properties.hibernate.dialect.storage_engine: innodb
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



logging:
  level:
    fon.productservice: debug
