server:
  port: 5555

spring:
  application:
    name: zuul-server
  session:
    store-type: redis


# http://localhost:5555/actuator/routes see all routes
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #url: http://localhost:4200
  routes:
    product-service: /product/**
    cart-service: /cart/**
    order-service: /order/**, /customer/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    fon.zuulserver: debug